In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from tensorflow.keras.layers import Dense, Flatten, Input, Dropout, SimpleRNN
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Model

In [1]:
# N- Number of samples
# T-sample length
# M-number of hidden units
# D-number of input features
# K-number of output units

In [21]:
N=3
D=3
T=10
K=2
X = np.random.randn(N, T, D)

In [22]:
X.shape

(3, 10, 3)

In [23]:
M = 5
i = Input(shape=(T,D))
x = SimpleRNN(5)(i)
x = Dense(K)(x)
model=Model(i, x)

In [24]:
yhat=model.predict(X)
yhat

array([[-0.40273103,  0.31304938],
       [-0.03804955, -0.35805455],
       [ 0.21548724, -0.43519872]], dtype=float32)

In [25]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.layers[1].get_weights()

[array([[-0.04246336,  0.04682392, -0.33272582,  0.24897546, -0.44122344],
        [ 0.18066329,  0.21223003, -0.26311016,  0.02133256, -0.54043627],
        [ 0.06317747,  0.7531721 , -0.8051059 , -0.6642943 , -0.6628533 ]],
       dtype=float32),
 array([[ 0.49150777, -0.04155034,  0.37260365,  0.57179177,  0.5393646 ],
        [ 0.5196326 , -0.42059857, -0.48894244, -0.4602093 ,  0.31972095],
        [ 0.08527198,  0.76332486, -0.58239377,  0.16342725,  0.21017373],
        [ 0.34463683, -0.23937327, -0.3498643 ,  0.52780396, -0.65034133],
        [ 0.6019602 ,  0.42591798,  0.40064237, -0.3949379 , -0.37382823]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [38]:
a, b, c=model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)  
# 1st weight is DxM which is input to hidden
# 2nd weight is MxM which is hidden to hidden
# 3rd is bias

(3, 5) (5, 5) (5,)


In [39]:
Wx, Wh, bh=model.layers[1].get_weights()
Wo, bo=model.layers[2].get_weights()

In [41]:
for i in range(N):
    h_last=np.zeros(M)
    x=X[i] #the one and only sample
    yhats=[]

    for t in range(T):
        h=np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
        y=h.dot(Wo) + bo
        yhats.append(y)

        h_last=h
    print(yhats[-1])

[-0.40273097  0.31304933]
[-0.0380495  -0.35805452]
[ 0.21548723 -0.43519871]
